### ISSUE TITLE
Unable to re-encrypt chef-vault item after rekeying with locally generated keys

### ISSUE THREAD

**Issue by chilicheech** [chef-cookbooks/client-rekey#3]
When I rekey a client with `local_key_generation = true` I am unable to re-encrypt chef-vault items. I get the following error: `ERROR: TypeError: no implicit conversion of nil into String`. After some debugging it seems that for some reason it is getting nil for the client's public_key. This isn't the case when I do server-side key generation. I'm still debugging but wanted to see if you guys have any insight on this.

**Comment by cheeseplus** [comment]
Closing as fixed by above patch.
